# Generated by Django 6.0.1 on 2026-07-01 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('tier_rank', models.PositiveSmallIntegerField(choices=[(1, 'Базовый'), (2, 'Премиум'), (3, 'VIP')], unique=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KZT', max_length=8)),
                ('yearly_discount_pct', models.PositiveSmallIntegerField(default=20, help_text='Скидка при годовой оплате, %')),
                ('max_visits_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('badge', models.CharField(blank=True, max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_categories', models.ManyToManyField(blank=True, help_text='Пусто = доступны все категории.', related_name='plans', to='partners.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('included', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='plans.plan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
