# Generated by Django 6.0.1 on 2026-07-01 05:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('icon', models.CharField(help_text='Имя иконки во фронтенде (см. Icon в components.jsx)', max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('tier_rank', models.PositiveSmallIntegerField(choices=[(1, 'Базовый'), (2, 'Премиум'), (3, 'VIP')], help_text='Минимальный тариф, открывающий доступ к заведению.')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Ключ терминала ресепшена для чек-ина (заголовок X-Partner-Key).', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='partners.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
